quarkus:
  http:
    port: ${PORT:8080}
  arc:
    exclude-types: com.abavilla.fpi.msgr.ext.rest.*
  mongodb:
    connection-string:
      ${MONGO_CONN_STRING:mongodb://localhost}
    database: ${DB_NAME}
  liquibase-mongodb:
    migrate-at-start: true
    change-log: db/changeLog.xml
    validate-on-migrate: true
    clean-at-start: false
  rest-client:
    connect-timeout: 120000
    read-timeout: 120000
    meta-graph-api:
      url: ${META_GRAPH_API_BASE_URI}
      scope: javax.inject.Singleton
  oidc:
    auth-server-url: ${OIDC_AUTH_URL:https://localhost:8543/realms/quarkus}
    client-id: ${OIDC_CLIENT_ID:backend-api}
    credentials:
      secret: ${OIDC_SECRET:AABBCC}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: true

com:
  meta:
    facebook:
      page-id: ${META_FB_PAGE_ID:ABCJSOWE1234}
      page-access-token: ${META_FB_PAGE_ACCESS_TOKEN:ABCJSOWE1234}